#!/bin/sh
# DESC: Elvi to search Chicago, IL Public Library Catalog
# elvis: cpl             -- Search Chicago Public Library (http://www.chipublib.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
    Search Chicago Public Library (http://www.chipublib.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://http://www.chipublib.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.chipublib.org/search/results/terms/${escaped_args}"
fi
