#!/bin/sh
# DESC: Elvi to search Harper College Library
# elvis: harperlibrary   -- Search Library (dept.harpercollege.edu/library/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
    Search Harper College Library (dept.harpercollege.edu/library/)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://dept.harpercollege.edu/library/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://harpercollege.summon.serialssolutions.com/search?s.q=${escaped_args}"
fi
