#!/bin/sh
# DESC: Elvi to search The Jargon File
# elvis: jargon          -- Search The Jargon File on catb.org
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
Search The Jargon File (www.catb.org/jargon/)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.catb.org/jargon"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.google.com/search?as_sitesearch=catb.org&as_q=${escaped_args}"
fi
