#!/bin/sh
# DESC: Elvi to search Morton Grove, IL Public Library Catalog
# elvis: mgpl            -- Search Morton Grove Public Library (www.mgpl.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
    Search Morton Grove Public Library (www.mgpl.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://mgpl.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://catalog.webrary.org/uhtbin/cgisirsi.exe/x/0/0/5/1?searchdata1=${escaped_args}"
fi
