#!/bin/sh
# DESC: Elvi to search Mount Prospect, IL Public Library Catalog
# elvis: mppl            -- Search Mount Prospect Public Library (www.mppl.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
    Search Mount Prospect Public Library (www.mppl.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.mppl.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://catalog.mppl.org/?q=${escaped_args}"
fi
