#!/bin/sh
# DESC: Elvi for Tumblr tags
# elvis: tumblr          -- Find Tumblr (www.tumblr.com) content by tag
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
    Find Tumblr (www.tumblr.com) content by tag
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.tumblr.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.tumblr.com/tagged/${escaped_args}"
fi
