#!/bin/sh
# DESC: Elvi to search Ustream
# elvis: ustream         -- Search Ustream (www.ustream.tv)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
Search Ustram (www.ustream.tv)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.ustream.tv"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.ustream.tv/new/search?q=${escaped_args}"
fi
